### PR TITLE
Fix building on EL8 kernels with drm backports up to 5.12

### LINKED ISSUE #331: Evdi does not compile on RedHat 8.5
* Are you using the latest driver?

Yes

  * Are you using the latest EVDI version?

Yes

  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?

Yes

  * Is this issue related to evdi/kernel?

Yes

  * Linux distribution and its version

Red Hat Enterprise Linux release 8.5 (Ootpa)

  * Linux kernel version

4.18.0-348.2.1.el8_5.x86_64

  * Xorg version (if used)

xorg-x11-server-Xwayland-21.1.1-6.el8

  * Desktop environment in use

gnome3

When trying to compile evdi, it fails as with:
````
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers -Werror=sign-compare " make -C module 
make[1]: Entering directory '/usr/src/evdi/module'
make -C /lib/modules/4.18.0-348.2.1.el8_5.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/4.18.0-348.2.1.el8_5.x86_64'
  CC [M]  /usr/src/evdi/module/evdi_platform_drv.o
  CC [M]  /usr/src/evdi/module/evdi_platform_dev.o
  CC [M]  /usr/src/evdi/module/evdi_sysfs.o
  CC [M]  /usr/src/evdi/module/evdi_modeset.o
/usr/src/evdi/module/evdi_modeset.c:180:20: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  .atomic_flush   = evdi_crtc_atomic_flush,
                    ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/evdi/module/evdi_modeset.c:180:20: note: (near initialization for ‘evdi_helper_funcs.atomic_flush’)
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:316: /usr/src/evdi/module/evdi_modeset.o] Error 1
make[2]: *** [Makefile:1571: _module_/usr/src/evdi/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.18.0-348.2.1.el8_5.x86_64'
make[1]: *** [Makefile:76: module] Error 2
make[1]: Leaving directory '/usr/src/evdi/module'
make: *** [Makefile:8: all] Error 2
`````

### PR DESCRIPTION
**Pull request by elguero**
The current kernel in RHEL8 and variants contain backports up to 5.12.  This patch adds the EL8 flag to the appropriate areas to work with these newer kernels.

These changes were tested on Rocky 8.5.

@dsommers reviewed these changes and did some testing with these changes.  He recommended (https://github.com/DisplayLink/evdi/pull/337#issuecomment-1003649717) merging this patch over the prior PR (https://github.com/DisplayLink/evdi/pull/337) that was submitted.

Fixes #331

### CODE REVIEW

**Comment by dsommers** [comment]
I agree, and I will close my pull request (#337) now to keep the path open for this one.

**Comment by displaylink-emajewsk** [comment]
Looks good, thanks!
