### ISSUE TITLE
Displaylink-driver-6.1.0-17.run  is not installed after updating to Kubuntu 25.04

### ISSUE THREAD

**Issue by thedemoncat** [DisplayLink/evdi#513]
``` 
sudo ./displaylink-driver-6.1.0-17.run 
Verifying archive integrity...  100%   MD5 checksums are OK. All good.
Uncompressing DisplayLink Linux Driver 6.1.0  100%  
Distribution discovered: Ubuntu 25.04

Installing
[ Installing EVDI ]
[[ Installing EVDI DKMS module ]]
Sign command: /usr/bin/kmodsign
Signing key: /var/lib/shim-signed/mok/MOK.priv
Public certificate (MOK): /var/lib/shim-signed/mok/MOK.der
Creating symlink /var/lib/dkms/evdi/1.14.7/source -> /usr/src/evdi-1.14.7

Building module:
Cleaning build area...
make -j16 KERNELRELEASE=6.14.0-15-generic all INCLUDEDIR=/lib/modules/6.14.0-15-generic/build/include KVERSION=6.14.0-15-generic DKMS_BUILD=1...(bad exit status: 2)
ERROR (dkms apport): binary package for evdi: 1.14.7 not found
Error! Bad return status for module build on kernel: 6.14.0-15-generic (x86_64)
Consult /var/lib/dkms/evdi/1.14.7/build/make.log for more information.
Deleting module evdi-1.14.7 completely from the DKMS tree.
ERROR: Failed to install evdi to the kernel tree.
```
installed versions via aptitude

**evdi-dkms** - 1.14.8+dfsg-1ubuntu1
**dkms** - 3.0.11-1ubuntu15

**Comment by jakub-prussak-synaptics** [comment]
Hello, could you retry with a deb package?  .run installer should be available soon. You can find the instructions [here](https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu).

**Comment by matheo** [comment]
@jakub-prussak-synaptics  I just upgraded to Ubuntu 25.04 and having the keyring already, I get something like:
```
Error: The package «displaylink-driver» doesn't have a candidate for installation
```

**Comment by nahoj** [comment]
I believe I had the same issue, just now when rebooting after upgrading from Kubuntu 24.10 to 25.04
- EVDI 1.14.7
- Linux 6.14.0-15-generic

Symptoms:

- Briefly saw some kind of stack trace early in the boot process, but could not find it again in dmesg, syslog or journald.
- Fans were running high.
- Package management could not build evdi because of some date issue.

In [make.log](https://github.com/user-attachments/files/20527123/make.log):

```
evdi_drm_drv.c:146:10: error: ‘struct drm_driver’ has no member named ‘date’
146 |         .date = DRIVER_DATE,
    |          ^~~~
```

As I am not using any DisplayLink device at the moment, I just uninstalled the `evdi` package. apt fixed itself and fans were back to normal after reboot.

**Comment by nahoj** [comment]
This issue would be fixed by PR https://github.com/DisplayLink/evdi/pull/510, by the looks of it.

**Comment by nahoj** [comment]
OK, if the fix has been merged already, I assume the error I had would be gone, though I don't have a reason to test it all at the moment.
