### ISSUE TITLE
fails to build on 4.12 kernel

### ISSUE THREAD

**Issue by InformatiQ** [DisplayLink/evdi#95]
/var/lib/dkms/evdi/1.4.1/build/evdi_modeset.c:294:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .page_flip = evdi_crtc_page_flip,
               ^~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.4.1/build/evdi_modeset.c:294:15: note: (near initialization for ‘evdi_crtc_funcs.page_flip’)
/var/lib/dkms/evdi/1.4.1/build/evdi_drv.c: In function ‘evdi_platform_probe’:
/var/lib/dkms/evdi/1.4.1/build/evdi_drv.c:120:9: error: implicit declaration of function ‘drm_platform_init’; did you mean ‘early_platform_init’? [-Werror=implicit-function-declaration]
  return drm_platform_init(&driver, pdev);
         ^~~~~~~~~~~~~~~~~
         early_platform_init
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:302: /var/lib/dkms/evdi/1.4.1/build/evdi_modeset.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:302: /var/lib/dkms/evdi/1.4.1/build/evdi_drv.o] Error 1
   ./tools/objtool/objtool check "/var/lib/dkms/evdi/1.4.1/build/evdi_connector.o";
  if [ "-pg" = "-pg" ]; then if [ /var/lib/dkms/evdi/1.4.1/build/evdi_connector.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/var/lib/dkms/evdi/1.4.1/build/evdi_connector.o"; fi; fi;
   ./tools/objtool/objtool check "/var/lib/dkms/evdi/1.4.1/build/evdi_encoder.o";
  if [ "-pg" = "-pg" ]; then if [ /var/lib/dkms/evdi/1.4.1/build/evdi_encoder.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/var/lib/dkms/evdi/1.4.1/build/evdi_encoder.o"; fi; fi;
make[1]: *** [Makefile:1519: _module_/var/lib/dkms/evdi/1.4.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/4.12.4-300.fc26.x86_64'

**Comment by InformatiQ** [comment]
using devel branch, which i use all teh time

**Comment by Scriptkiddi** [comment]
so I tried to find the reason for this error turns out drm_platform_init is deprecated(https://01.org/linuxgraphics/gfx-docs/drm/API-drm-platform-init.html) and was removed in kernel 4.12 instead one should use drm_dev_alloc and drm_dev_register, but thats where my knowledge leaves me since I'm not C programmer all I could do was to track the error to its source. Hopping this helps

**Comment by Project0** [comment]
seems to be fixed in devel branch  6c689d69457820512f25204d83f0880824a932f3

**Comment by InformatiQ** [comment]
my mistake, I was building an old SHA by err
Sorry for the noise
