### ISSUE TITLE
Evdi does not compile on RedHat 8.5

### ISSUE THREAD

**Issue by rickettmwork** [DisplayLink/evdi#331]
* Are you using the latest driver?

Yes

  * Are you using the latest EVDI version?

Yes

  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?

Yes

  * Is this issue related to evdi/kernel?

Yes

  * Linux distribution and its version

Red Hat Enterprise Linux release 8.5 (Ootpa)

  * Linux kernel version

4.18.0-348.2.1.el8_5.x86_64

  * Xorg version (if used)

xorg-x11-server-Xwayland-21.1.1-6.el8

  * Desktop environment in use

gnome3

When trying to compile evdi, it fails as with:
````
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers -Werror=sign-compare " make -C module 
make[1]: Entering directory '/usr/src/evdi/module'
make -C /lib/modules/4.18.0-348.2.1.el8_5.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/4.18.0-348.2.1.el8_5.x86_64'
  CC [M]  /usr/src/evdi/module/evdi_platform_drv.o
  CC [M]  /usr/src/evdi/module/evdi_platform_dev.o
  CC [M]  /usr/src/evdi/module/evdi_sysfs.o
  CC [M]  /usr/src/evdi/module/evdi_modeset.o
/usr/src/evdi/module/evdi_modeset.c:180:20: error: initialization of ‘void (*)(struct drm_crtc *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_crtc *, struct drm_crtc_state *)’ [-Werror=incompatible-pointer-types]
  .atomic_flush   = evdi_crtc_atomic_flush,
                    ^~~~~~~~~~~~~~~~~~~~~~
/usr/src/evdi/module/evdi_modeset.c:180:20: note: (near initialization for ‘evdi_helper_funcs.atomic_flush’)
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:316: /usr/src/evdi/module/evdi_modeset.o] Error 1
make[2]: *** [Makefile:1571: _module_/usr/src/evdi/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.18.0-348.2.1.el8_5.x86_64'
make[1]: *** [Makefile:76: module] Error 2
make[1]: Leaving directory '/usr/src/evdi/module'
make: *** [Makefile:8: all] Error 2
`````

**Comment by rickettmwork** [comment]
Looking at the code I am guessing that redhat have backported stuff from 5.11+ kernels, and it might be a case of another flag like the EL8 flag to pick the right one
