### ISSUE TITLE
Fedora 31 fails to compile evdi

### ISSUE THREAD

**Issue by msandres13** [DisplayLink/evdi#198]
Fedora 31:
Linux xxxxx 5.5.17-200.fc31.x86_64 #1 SMP Mon Apr 13 15:29:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
evdi/1.6.4

Path to Error:
Install prereqs for building kernel-devel, dkms, bison, flex, ....
sudo dnf install https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.2.14-2/fedora-31-displaylink-1.6.4-1.x86_64.rpm

Error Message:
[make.log](https://github.com/DisplayLink/evdi/files/4534817/make.log)
make -f ./scripts/Makefile.modbuiltin obj=kernel/debug
make -f ./scripts/Makefile.modbuiltin obj=security/selinux
/usr/src/kernels/5.5.17-200.fc31.x86_64/tools/build/Makefile.build:37: /usr/src/kernels/5.5.17-200.fc31.x86_64/tools/build/Build.include: No such file or directory
make[5]: *** No rule to make target '/usr/src/kernels/5.5.17-200.fc31.x86_64/tools/build/Build.include'.  Stop.
make[4]: *** [Makefile:43: /usr/src/kernels/5.5.17-200.fc31.x86_64/tools/objtool/fixdep-in.o] Error 2
make[3]: *** [/usr/src/kernels/5.5.17-200.fc31.x86_64/tools/build/Makefile.include:5: fixdep] Error 2
make -f ./scripts/Makefile.modbuiltin obj=block
make[2]: *** [Makefile:67: objtool] Error 2
make[1]: *** [Makefile:1797: tools/objtool] Error 2

**Comment by msandres13** [comment]
I also tried the prerelease v5.2.14-3-rc1, here the result looks like this.
[make.log](https://github.com/DisplayLink/evdi/files/4534826/make.log)

/var/lib/dkms/evdi/1.6.4/build/evdi_drv.c:11:10: fatal error: drm/drmP.h: No such file or directory
   11 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
/var/lib/dkms/evdi/1.6.4/build/evdi_modeset.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
/var/lib/dkms/evdi/1.6.4/build/evdi_connector.c:14:10: fatal error: drm/drmP.h: No such file or directory
   14 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_drv.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_modeset.o] Error 1
/var/lib/dkms/evdi/1.6.4/build/evdi_encoder.c:14:10: fatal error: drm/drmP.h: No such file or directory
   14 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_connector.o] Error 1
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_encoder.o] Error 1
/var/lib/dkms/evdi/1.6.4/build/evdi_gem.c:11:10: fatal error: drm/drmP.h: No such file or directory
   11 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_gem.o] Error 1
/var/lib/dkms/evdi/1.6.4/build/evdi_main.c:15:10: fatal error: drm/drmP.h: No such file or directory
   15 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_main.o] Error 1
/var/lib/dkms/evdi/1.6.4/build/evdi_painter.c:12:10: fatal error: drm/drmP.h: No such file or directory
   12 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_painter.o] Error 1
/var/lib/dkms/evdi/1.6.4/build/evdi_fb.c:20:10: fatal error: drm/drmP.h: No such file or directory
   20 | #include <drm/drmP.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:266: /var/lib/dkms/evdi/1.6.4/build/evdi_fb.o] Error 1
make[1]: *** [Makefile:1694: /var/lib/dkms/evdi/1.6.4/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.5.17-200.fc31.x86_64'
make: *** [Makefile:22: all] Error 2

**Comment by msandres13** [comment]
The fail for the prerelease seems to be handled in #185

**Comment by elguero** [comment]
It would appear that you have created the issue to the wrong repo.  The rpms you reference are not maintained by the evdi team.

This issue has been solved by the evdi team and current master of displaylink-rpm is able to build against the devel branch of evdi.

https://github.com/displaylink-rpm/displaylink-rpm/issues/121

**Comment by msandres13** [comment]
Of course, you are correct.
I learned that investiating in the problem.
I will close the ticket.

Thanks for the reminder
