### ISSUE TITLE
evdi-1.9.1 does not build on RHEL-8.4 (4.18.0-305.el8.x86_64)

### ISSUE THREAD

**Issue by dsommers** [DisplayLink/evdi#283]
Linux distro: Red Hat Enterprise Linux 8.4
Kernel version: 4.18.0-305.el8.x86_64
Arch: x86_64

```
~/dev/evdi-1.9.1 # make
CFLAGS="-Werror -Wextra -Wall -Wmissing-prototypes -Wstrict-prototypes -Wno-error=missing-field-initializers " make -C module 
make[1]: Entering directory '/root/dev/evdi-1.9.1/module'
make -C /lib/modules/4.18.0-305.el8.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/4.18.0-305.el8.x86_64'
  CC [M]  /root/dev/evdi-1.9.1/module/evdi_platform_drv.o
  CC [M]  /root/dev/evdi-1.9.1/module/evdi_platform_dev.o
/root/dev/evdi-1.9.1/module/evdi_platform_dev.c: In function ‘evdi_platform_device_probe’:
/root/dev/evdi-1.9.1/module/evdi_platform_dev.c:82:20: error: ‘struct dev_archdata’ has no member named ‘iommu’
  pdev->dev.archdata.iommu = INTEL_IOMMU_DUMMY_DOMAIN;
                    ^
make[3]: *** [scripts/Makefile.build:316: /root/dev/evdi-1.9.1/module/evdi_platform_dev.o] Error 1
make[2]: *** [Makefile:1563: _module_/root/dev/evdi-1.9.1/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/4.18.0-305.el8.x86_64'
make[1]: *** [Makefile:77: module] Error 2
make[1]: Leaving directory '/root/dev/evdi-1.9.1/module'
make: *** [Makefile:8: all] Error 2
```

**Comment by KeXu001** [comment]
The latest rhel/centos release uses newer drm/dev layer stuff. I'm not a linux guy but it looks like the kernel versions are not really comparable across distributions. So, adding rhel compatibility is a little troublesome(?)

If you want a really ugly workaround you can change some of the macro parameters so that the correct functions are called
https://github.com/KeXu001/evdi/commit/0e2af9ec929f5d229f246bad3cf29f54609d098a

**Comment by elguero** [comment]
Yep, RH chooses what to backport to their distro.  That means you cannot just go by the kernel version that is being used.

**Comment by dsommers** [comment]
Just did a quick build/compile from git based on @elguero's repository.  It builds fine on RHEL-8.4.  I have not yet tested the module nor the evdi library.
