### ISSUE TITLE
evdi module failed to build again linux kernel 4.19.91

### ISSUE THREAD

**Issue by noraj** [DisplayLink/evdi#176]
## Description

evdi module failed to build again linux kernel 4.19.91

## Troubleshooting

During the systemd init boot I see a message like `|displaylink.service failed to start`.

So after startup I did check the status of the service:

```
➜ sudo systemctl status displaylink.service                                                                                                                                                     
[sudo] password for noraj:                                                                                                                                                                      
● displaylink.service - DisplayLink Manager Service                                                                                                                                             
     Loaded: loaded (/usr/lib/systemd/system/displaylink.service; disabled; vendor preset: disabled)                                                                                            
     Active: activating (auto-restart) (Result: exit-code) since Mon 2019-12-23 11:26:16 CET; 1s ago                                                                                            
    Process: 1350 ExecStartPre=/sbin/modprobe evdi (code=exited, status=1/FAILURE)
```

And I went to see what the service config file is containing:

```
➜ sudo systemctl cat displaylink.service                                                                                                                                                        
# /usr/lib/systemd/system/displaylink.service                                                                                                                                                   
[Unit]                                                                                                                                                                                          
Description=DisplayLink Manager Service                                                                                                                                                         
After=display-manager.service                                                                                                                                                                   
Conflicts=getty@tty7.service                                                                                                                                                                    
                                                                                                                                                                                                
[Service]                                                                                                                                                                                       
ExecStartPre=/sbin/modprobe evdi                                                                                                                                                                
ExecStart=/usr/lib/displaylink/DisplayLinkManager                                                                                                                                               
Restart=always                                                                                                                                                                                  
WorkingDirectory=/usr/lib/displaylink                                                                                                                                                           
RestartSec=5                                                                                                                                                                                    
                                                                                                                                                                                                
[Install]                                                                                                                                                                                       
WantedBy=graphical.target                                                                                                                                                                       
```

So I tried to start the evdi kernel module manually:

```
➜ sudo modprobe evdi                                                                                                                                                                            
modprobe: FATAL: Module evdi not found in directory /lib/modules/4.19.91-1-lts
```

The error suggest the module was not successfully built for this kernel.

So I checked built modules:

```
➜ sudo dkms status
evdi, 1.6.4, 5.4.6-arch1-1, x86_64: installed
vboxhost, 6.1.0_OSE, 4.19.91-1-lts, x86_64: installed
vboxhost, 6.1.0_OSE, 5.4.6-arch1-1, x86_64: installed
```

Effectively evdi is built against 5.4.6 kernel but not  4.19.91.

I tried to build it manually:

```
sudo dkms build -m evdi -v 1.6.4 -k 4.19.91-1-lts -a x86_64

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=4.19.91-1-lts all INCLUDEDIR=/lib/modules/4.19.91-1-lts/build/include KVERSION=4.19.91-1-lts DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.19.91-1-lts (x86_64)
Consult /var/lib/dkms/evdi/1.6.4/build/make.log for more information.
```

The last lines of the logs are:

```
➜ tail /var/lib/dkms/evdi/1.6.4/build/make.log
/var/lib/dkms/evdi/1.6.4/build/evdi_modeset.c:480: error: expected ‘{’ at end of input
  480 | }
      | 
/var/lib/dkms/evdi/1.6.4/build/evdi_modeset.c:480:1: warning: control reaches end of non-void function [-Wreturn-type]
  480 | }
      | ^
make[2]: *** [scripts/Makefile.build:303: /var/lib/dkms/evdi/1.6.4/build/evdi_modeset.o] Error 1
make[1]: *** [Makefile:1522: _module_/var/lib/dkms/evdi/1.6.4/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.19.91-1-lts/build'
make: *** [Makefile:22: all] Error 2
```

Full logs: https://gist.github.com/noraj/93372f60dac56637038cd4338492e285

## Template & context

Initially please make sure the problem hasn't been already addressed:
  * [x] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [x] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [x] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [x] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version: ArchLinux
  * Linux kernel version: 4.19.91-1-lts
  * Desktop environment in use: KDE

**Comment by noraj** [comment]
## Reason

I was using [evdi](https://aur.archlinux.org/packages/evdi/) AUR package, and as said in https://github.com/DisplayLink/evdi/issues/173 the AUR package include a 5.4 patch but the 5.4 patch make it crash against 4.19 so a [4.19 AUR package fork](https://aur.archlinux.org/packages/evdi-4.19/) was created for that. It's very far from ideal, so if you could patch the evdi module so it works against both 4.19 and 5.4.

**Comment by displaylink-dkurek** [comment]
Thanks for great report (with all those information, troubleshooting and conclusion!)
Closing :)
