### ISSUE TITLE
Issue with Linux mint 18.3 kernal 4.19

### ISSUE THREAD

**Issue by robin31** [DisplayLink/evdi#139]
Getting following error in latest Mint 18.3  4.19 kernal

```
DKMS make.log for evdi-4.2.29 for kernel 4.19.0-041900rc5-generic (x86_64)
Wed Sep 26 17:09:45 CEST 2018
make KBUILD_VERBOSE=1 SUBDIRS=/var/lib/dkms/evdi/4.2.29/build SRCROOT=/var/lib/dkms/evdi/4.2.29/build CONFIG_MODULE_SIG= -C /lib/modules/4.19.0-041900rc5-generic/build modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.0-041900rc5-generic'
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
mkdir -p /var/lib/dkms/evdi/4.2.29/build/.tmp_versions ; rm -f /var/lib/dkms/evdi/4.2.29/build/.tmp_versions/*
make -f ./scripts/Makefile.build obj=/var/lib/dkms/evdi/4.2.29/build
(cat /dev/null;   echo kernel//var/lib/dkms/evdi/4.2.29/build/evdi.ko;) > /var/lib/dkms/evdi/4.2.29/build/modules.order
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_drv.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_drv"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_drv.o /var/lib/dkms/evdi/4.2.29/build/evdi_drv.c
   ./tools/objtool/objtool check  --module --retpoline "/var/lib/dkms/evdi/4.2.29/build/evdi_drv.o";
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_modeset.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_modeset"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_modeset.o /var/lib/dkms/evdi/4.2.29/build/evdi_modeset.c
   ./tools/objtool/objtool check  --module --retpoline "/var/lib/dkms/evdi/4.2.29/build/evdi_modeset.o";
  gcc -Wp,-MD,/var/lib/dkms/evdi/4.2.29/build/.evdi_connector.o.d  -nostdinc -isystem /usr/lib/gcc/x86_64-linux-gnu/5/include -I./arch/x86/include -I./arch/x86/include/generated  -I./include -I./arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I./include/uapi -I./include/generated/uapi -include ./include/linux/kconfig.h -include ./include/linux/compiler_types.h -D__KERNEL__ -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -Werror-implicit-function-declaration -Wno-format-security -std=gnu89 -fno-PIE -DCC_HAVE_ASM_GOTO -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -m64 -falign-jumps=1 -falign-loops=1 -mno-80387 -mno-fp-ret-in-387 -mpreferred-stack-boundary=3 -mskip-rax-setup -mtune=generic -mno-red-zone -mcmodel=kernel -funit-at-a-time -DCONFIG_X86_X32_ABI -DCONFIG_AS_CFI=1 -DCONFIG_AS_CFI_SIGNAL_FRAME=1 -DCONFIG_AS_CFI_SECTIONS=1 -DCONFIG_AS_FXSAVEQ=1 -DCONFIG_AS_SSSE3=1 -DCONFIG_AS_CRC32=1 -DCONFIG_AS_AVX=1 -DCONFIG_AS_AVX2=1 -DCONFIG_AS_AVX512=1 -DCONFIG_AS_SHA1_NI=1 -DCONFIG_AS_SHA256_NI=1 -pipe -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -DRETPOLINE -fno-delete-null-pointer-checks -O2 --param=allow-store-data-races=0 -Wframe-larger-than=1024 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Iinclude/drm  -DMODULE  -DKBUILD_BASENAME='"evdi_connector"' -DKBUILD_MODNAME='"evdi"' -c -o /var/lib/dkms/evdi/4.2.29/build/evdi_connector.o /var/lib/dkms/evdi/4.2.29/build/evdi_connector.c
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c: In function ‘evdi_get_modes’:
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c:34:3: error: implicit declaration of function ‘drm_mode_connector_update_edid_property’ [-Werror=implicit-function-declaration]
   drm_mode_connector_update_edid_property(connector, NULL);
   ^
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c: In function ‘evdi_connector_init’:
/var/lib/dkms/evdi/4.2.29/build/evdi_connector.c:146:2: error: implicit declaration of function ‘drm_mode_connector_attach_encoder’ [-Werror=implicit-function-declaration]
  drm_mode_connector_attach_encoder(connector, encoder);
  ^
cc1: some warnings being treated as errors
scripts/Makefile.build:305: recipe for target '/var/lib/dkms/evdi/4.2.29/build/evdi_connector.o' failed
make[2]: *** [/var/lib/dkms/evdi/4.2.29/build/evdi_connector.o] Error 1
Makefile:1515: recipe for target '_module_/var/lib/dkms/evdi/4.2.29/build' failed
make[1]: *** [_module_/var/lib/dkms/evdi/4.2.29/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.19.0-041900rc5-generic'
Makefile:22: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by mrTsjolder** [comment]
Did you [install the kernel headers](http://ask.xmodulo.com/install-kernel-headers-linux.html)?

**Comment by robin31** [comment]
@kugel- Tested it by modifying files from the commit directly in the installer. 
Works like a charm.

Should be updated asap in drivers on website for all new Linux installs.

Seems like travis is giving an error on codestyle though?

**Comment by adangel** [comment]
Seems to be fixed with evdi 1.5.1
-> https://github.com/DisplayLink/evdi/releases/tag/v1.5.1

Fixed via https://github.com/DisplayLink/evdi/commit/c7e80bc32c2ef96464613fbbda15fd930bf6fb41

**Comment by robin31** [comment]
im not 100% sure as it says "EVDI driver used in DisplayLink Ubuntu Software v4.4"
4.4 is currently not working with 4.19. Just tested it.

**Comment by robin31** [comment]
update. 1.5.1 is fixed but it says 1.5.1 is in display link 4.4 drivers. This is not the case 4.4.24 is in the ubuntu display link 4.4 drivers. Thus all new linux install will not work with that version.

**Comment by AdnanHodzic** [comment]
I'm the author of [displaylink-debian tool](https://github.com/AdnanHodzic/displaylink-debian) and same issue was [brought up on our side](https://github.com/AdnanHodzic/displaylink-debian/issues/191). 

Since we're not sure when the fix will get fully rolled out, I decided to [implementa patch as part of displaylink-debian](https://github.com/AdnanHodzic/displaylink-debian/blob/nexgen-kernel/displaylink-debian.sh#L331) if kernel >= 4.19 is detected. 

However making same changes as they were done in: https://github.com/DisplayLink/evdi/commit/c7e80bc32c2ef96464613fbbda15fd930bf6fb41 doesn't seem to work.

Error I end up with on both Debian Buster and Ubuntu Bionic with 4.19/20 kernel is just:
```
ERROR (code 2): Unable to add evdi/4.4.24 to DKMS source tree..
```

Hence, since both @adangel @robin31 of you said you made it work by applying same changes could you tell me what I'm doing wrong?

**Comment by adangel** [comment]
@AdnanHodzic The error occurs, if there is already a dkms module evdi/4.4.24. It seems, that the uninstall logic stopped working, that's why the module is still there from the previous installation. I've fixed that as well in https://github.com/AdnanHodzic/displaylink-debian/pull/199.

You can manually cleanup by executing:

    sudo dkms remove evdi/4.4.24 --all
    sudo rm -rf /usr/src/evdi-4.2.24

**Comment by AdnanHodzic** [comment]
JFYI, thanks to @adangel's help [displaylink-debian](https://github.com/AdnanHodzic/displaylink-debian) now also works and lets you install DisplayLink with 4.19 kernel.

**Comment by displaylink-dkurek** [comment]
evdi repository has been updated with quite some number of changes.
We are shifting towards 'atomic modeset', which means we are dropping 
support for kernels older than 4.2. It also supports 4.19 and 4.20. Finally :)

With this change we did bump-up the evdi/libevdi versions, so for compatibility
please install new DisplayLinkManager (v5.1), which can be downloaded from here:
https://www.displaylink.com/downloads/ubuntu 
Hope you will like it and it will fix your problems with 4.19 compilation.

Will close the issue.
