### ISSUE TITLE
DKMS build fails to build evdi module with kernel 5.4.64-1 Manjaro Linux

### ISSUE THREAD

**Issue by d3nwah** [DisplayLink/evdi#221]
Initially please make sure the problem hasn't been already addressed:
  * [ ] Are you using the latest driver?
    (https://www.displaylink.com/downloads/ubuntu)
  * [ ] Are you using the latest EVDI version?
    (https://github.com/DisplayLink/evdi/releases)
  * [ ] If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website?
    (https://support.displaylink.com/knowledgebase/topics/103927-troubleshooting-ubuntu)
  * [ ] Is this issue related to evdi/kernel?
    (if it is rather connected to DisplayLinkManager please take a look at support
    https://support.displaylink.com or forum https://www.displaylink.org/forum/)

Some information for baseline would help a lot:
  * Linux distribution and its version Manjaro Linux 20.1
  * Linux kernel version 5.4.64-1-MANJARO
  * Xorg version (if used) X.Org X Server 1.20.8
  * Desktop environment in use XFCE 4.14

Compilation log: https://pastebin.com/Cd0Nqgw3
Make log: https://pastebin.com/AAHHzLYD

I'm trying to install evdi through AUR, using pamac-manager which says it's the current 1.8.0 version. I have never used evdi before (at least not successfully), so please forgive me if it's somehow something on my end. The distro is upgraded to the newest rolling release.

( TLDR version
>/var/lib/dkms/evdi/1.8.0/build/evdi_connector.c:117:9: error: too many arguments to function ‘drm_encoder_find’
  117 |  return drm_encoder_find(connector->dev,
      |         ^~~~~~~~~~~~~~~~
In file included from ./include/drm/drm_modeset_helper_vtables.h:33,
                 from ./include/drm/drm_crtc_helper.h:43,
                 from /var/lib/dkms/evdi/1.8.0/build/evdi_connector.c:17:
./include/drm/drm_encoder.h:216:35: note: declared here
  216 | static inline struct drm_encoder *drm_encoder_find(struct drm_device *dev,
      |                                   ^~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.8.0/build/evdi_drv.c: In function ‘evdi_platform_probe’:
/var/lib/dkms/evdi/1.8.0/build/evdi_drv.c:193:2: error: implicit declaration of function ‘drm_dev_put’; did you mean ‘pci_dev_put’? [-Werror=implicit-function-declaration]
  193 |  drm_dev_put(dev);
      |  ^~~~~~~~~~~
      |  pci_dev_put
/var/lib/dkms/evdi/1.8.0/build/evdi_fb.c:255:15: error: ‘DRM_MODESET_ACQUIRE_INTERRUPTIBLE’ undeclared (first use in this function)
  255 |   file_priv ? DRM_MODESET_ACQUIRE_INTERRUPTIBLE : 0);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.8.0/build/evdi_fb.c:255:15: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/evdi/1.8.0/build/evdi_fb.c:292:7: error: void value not ignored as it ought to be
  292 |   ret = drm_modeset_backoff(&ctx);
      |       ^

)

**Comment by displaylink-dkurek** [comment]
In **compilation** log
```
==> dkms install --no-depmod -m evdi -v 1.8.0 -k 4.14.197-1-MANJARO
Error! Bad return status for module build on kernel: 4.14.197-1-MANJARO (x86_64)
Error while configuring 
Consult /var/lib/dkms/evdi/1.8.0/build/make.log for more information.
```
And in **/var/lib/dkms/evdi/1.8.0/build/make.log**
```
DKMS make.log for evdi-1.8.0 for kernel 4.14.197-1-MANJARO (x86_64)
```

Seems you have multiple kernel versions installed (4.14 being one of them).
EVDI supports kernels from 4.15.
Could you please uninstall 4.14 (you may also consider removing other ones)
and try again?

**Comment by d3nwah** [comment]
You were completely right, my apologies.

**Comment by displaylink-dkurek** [comment]
No problem, glad it helped :)
