### ISSUE TITLE
Unable to build on kernel 5.13

### ISSUE THREAD

**Issue by cryocz** [DisplayLink/evdi#297]
Unable to build evdi v1.9.1 on `5.13.4-200.fc34.x86_64`.

 # Setup
  * Are you using the latest EVDI version? *Yes, v1.9.1*
  * Is this issue related to evdi/kernel? *Yes*
  * Linux distribution and its version: *Fedora 34*
  * Linux kernel version: *5.13.4*
  * Xorg version (if used): *1.20.11 (according to `rpm -qa | grep xorg-x11-server-Xorg`)*
  * Desktop environment in use: *GNOME 40.0*

# Steps to reproduce
```console
$ sudo dkms install -m evdi -v 1.9.1 -k 5.13.4-200.fc34.x86_64/x86_64

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j8 KERNELRELEASE=5.13.4-200.fc34.x86_64 all INCLUDEDIR=/lib/modules/5.13.4-200.fc34.x86_64/build/include KVERSION=5.13.4-200.fc34.x86_64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.13.4-200.fc34.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.9.1/build/make.log for more information.
```

Errors found in `/var/lib/dkms/evdi/1.9.1/build/make.log`:
```
/var/lib/dkms/evdi/1.9.1/build/evdi_modeset.c:331:26: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  331 |         .atomic_update = evdi_plane_atomic_update,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.9.1/build/evdi_modeset.c:331:26: note: (near initialization for ‘evdi_plane_helper_funcs.atomic_update’)
/var/lib/dkms/evdi/1.9.1/build/evdi_modeset.c:332:23: error: ‘drm_gem_fb_prepare_fb’ undeclared here (not in a function); did you mean ‘drm_gem_fb_create’?
  332 |         .prepare_fb = drm_gem_fb_prepare_fb
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       drm_gem_fb_create
/var/lib/dkms/evdi/1.9.1/build/evdi_modeset.c:336:26: error: initialization of ‘void (*)(struct drm_plane *, struct drm_atomic_state *)’ from incompatible pointer type ‘void (*)(struct drm_plane *, struct drm_plane_state *)’ [-Werror=incompatible-pointer-types]
  336 |         .atomic_update = evdi_cursor_atomic_update,
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.9.1/build/evdi_modeset.c:336:26: note: (near initialization for ‘evdi_cursor_helper_funcs.atomic_update’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:273: /var/lib/dkms/evdi/1.9.1/build/evdi_modeset.o] Error 1
make[1]: *** [Makefile:1853: /var/lib/dkms/evdi/1.9.1/build] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.13.4-200.fc34.x86_64'
make: *** [Makefile:28: all] Error 2
```

**Comment by elguero** [comment]
Until there is a new release, you need to use the code in the devel branch to build against 5.13.

(Duplicate of #296)

**Comment by olof-nord** [comment]
Is kernel 5.13 planned to be supported? 
My docking station stopped working (again) with v5.13.

I see no mention of it in the [CI config](https://github.com/DisplayLink/evdi/blob/devel/.travis.yml#L6).

Any estimation when an upcoming release is planned?

**Comment by xtermi2** [comment]
Same on Ubuntu 21.04 with 5.13 mainline kernel.

**Comment by carestad** [comment]
From the commit log, 5.14 support was added recently so I would hope and think 5.13 is also supported now? But would have to build it manually though

**Comment by carestad** [comment]
I found a way to make the DisplayLink driver work with the 5.13 kernel in PopOS 21.04. I added a step-by-step [in the DisplayLink forum](https://www.displaylink.org/forum/showpost.php?p=92453&postcount=3). It might be applicable to some of the cases in here as well.

**Comment by xtermi2** [comment]
@carestad thx, works with 5.13 on Ubuntu 21.04

**Comment by dongsupark** [comment]
@carestad Thanks a lot.
It works with Kernel 5.13 on Fedora 34.
Though I had to disable `check_libdrm` in the script, as the function simply assumes Debian-specific commands like `apt` exist.

```
--- displaylink-installer.sh.orig       2021-08-16 11:11:02.115185859 +0200
+++ displaylink-installer.sh    2021-08-16 11:03:20.480823052 +0200
@@ -568,8 +568,8 @@
   # DKMS
   hash dkms 2>/dev/null || missing_requirement "DKMS"
 
-  # libdrm
-  check_libdrm || missing_requirement "libdrm"
+  ## libdrm
+  #check_libdrm || missing_requirement "libdrm"
 
   # Required kernel version
   KVER=$(uname -r)
```

**Comment by derDaywalker** [comment]
@carestad Thanks a lot, works like a charm. 

I had to append -L to curl to follow a redirect

```
curl -L https://github.com/DisplayLink/evdi/archive/refs/heads/devel.tar.gz -o evdi.tar.gz
```

@dongsupark 
Also thank you very much, I had to do this too, although libdrm is installed, but yes, on arch there is no apt too. 

Now everything works again on 5.13.12-arch1-1

**Comment by carestad** [comment]
> I had to append -L to curl to follow a redirect
> 
> ```
> curl -L https://github.com/DisplayLink/evdi/archive/refs/heads/devel.tar.gz -o evdi.tar.gz
> ```
> 

Cheers, I updated the forum post with this :slightly_smiling_face:

**Comment by YoannMa** [comment]
@carestad Hi, would you mind posting the copy of your step-by-step here (or on Gist ?) as the DisplayLink forum seems down

**Comment by edwade** [comment]
> I found a way to make the DisplayLink driver work with the 5.13 kernel in PopOS 21.04. I added a step-by-step [in the DisplayLink forum](https://www.displaylink.org/forum/showpost.php?p=92453&postcount=3). It might be applicable to some of the cases in here as well.

Thank you @carestad - got me back up and running Ubuntu 21.10 (Impish)! Absolute lifesaver!
