### PR TITLE
Add support for kernel 6.0 + a minor fix

### PR DESCRIPTION
**Pull request by SimPilotAdamT**
Fixes https://github.com/DisplayLink/evdi/issues/376 by implementing @Crashdummyy's fix as posted [here](https://github.com/DisplayLink/evdi/issues/376#issuecomment-1237450695), +  fixes the style used in evdi_painter.c 

Before submitting the PR please make sure you have run *ci* scripts:
  * `./ci/build_against_kernel` (see `--help` for all options) (done)
    We need backward compatibility and this script is a handy way of testing
    build compliance with many kernel versions.
  * `./ci/run_style_check` (done)
    We want to be as style compliant as possible. Again, this is a handy way of
    checking it.

If you have more than one change consider creating separate PRs for them; it
will make the review process much easier. Also provide some description (links
to source code or mailing list are welcome - this might help to understand the
change).

Thanks for the contribution!

### CODE REVIEW

**Comment by SimPilotAdamT** [comment]
I think there needs to be more updates to make it fully function.. While the fix works for OP of the issue this aims to fix, I still can't get the DKMS package to properly install. Also it fails to build on some older Kernels.

**Comment by SimPilotAdamT** [comment]
This works for me. I am by no means a C programmer, but I think there needs to be a way to make sure the `#include <drm/drm_framebuffer.h>` line added to `module/evdi_drm_drv.h` is only done on Kernel versions 6.0.0 and newer. I have no clue how to do this... What about you guys?

**Comment by SimPilotAdamT** [comment]
Oh I think ik how to do it, commit coming soon

**Comment by SimPilotAdamT** [comment]
OK that's done... I do have an issue using the CI build script checking the build on Kernel versions older than 5.17...

Here is the error, which really stems from a warning using `-Werror`
```c
  CC      /home/adam/evdi/tmp/linux-5.16/tools/objtool/help.o
In file included from help.c:12:
In function ‘xrealloc’,
    inlined from ‘add_cmdname’ at help.c:24:2:
subcmd-util.h:56:23: error: pointer may be used after ‘realloc’ [-Werror=use-after-free]
   56 |                 ret = realloc(ptr, size);
      |                       ^~~~~~~~~~~~~~~~~~
subcmd-util.h:52:21: note: call to ‘realloc’ here
   52 |         void *ret = realloc(ptr, size);
      |                     ^~~~~~~~~~~~~~~~~~
subcmd-util.h:58:31: error: pointer may be used after ‘realloc’ [-Werror=use-after-free]
   58 |                         ret = realloc(ptr, 1);
      |                               ^~~~~~~~~~~~~~~
subcmd-util.h:52:21: note: call to ‘realloc’ here
   52 |         void *ret = realloc(ptr, size);
      |                     ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[4]: *** [/home/adam/evdi/tmp/linux-5.16/tools/build/Makefile.build:97: /home/adam/evdi/tmp/linux-5.16/tools/objtool/help.o] Error 1
make[3]: *** [Makefile:59: /home/adam/evdi/tmp/linux-5.16/tools/objtool/libsubcmd-in.o] Error 2
make[2]: *** [Makefile:63: /home/adam/evdi/tmp/linux-5.16/tools/objtool/libsubcmd.a] Error 2
make[1]: *** [Makefile:69: objtool] Error 2
make: *** [Makefile:1349: tools/objtool] Error 2
```

**Comment by SimPilotAdamT** [comment]
(changed again bc I'm so dumb and couldn't fathom `>=` and `<=`)

**Comment by SimPilotAdamT** [comment]
*ok **__now__** it should properly work, don't quote me on that*

**Comment by displaylink-emajewsk** [comment]
Thanks for the PR, looks good, but let me verify it

**Comment by displaylink-emajewsk** [comment]
> Is anyone able to help me test smth? The CI build script passes [this branch](https://github.com/SimPilotAdamT/evdi/tree/test/) on my repo on kernel versions 5.16 and newer, but I'm not sure if it will actually install the module properly... I don't have a machine I can test on myself

Seems fine to me. If you merge those branches, we can pull it in. We'll do a thorough testing before a release :)

**Comment by SimPilotAdamT** [comment]
> Seems fine to me. If you merge those branches, we can pull it in. We'll do a thorough testing before a release :)

Merged

**Comment by dimitarsh1** [comment]
I just updated to kernel 6 on Debian testing

I get the following: 

```
$ sudo dkms install -m evdi -v 1.12.0
Sign command: /usr/lib/linux-kbuild-6.0/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j8 KERNELRELEASE=6.0.0-2-amd64 all INCLUDEDIR=/lib/modules/6.0.0-2-amd64/build/include KVERSION=6.0.0-2-amd64 DKMS_BUILD=1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.0.0-2-amd64 (x86_64)
Consult /var/lib/dkms/evdi/1.12.0/build/make.log for more information.
```

I have pulled the latest devel update. 

Any suggestions

**Comment by SimPilotAdamT** [comment]
@Crashdummyy whaddaya think?

**Comment by SimPilotAdamT** [comment]
> Any suggestions

Can you send that `make.log` file?

**Comment by dimitarsh1** [comment]
Yup, here it is.

[make.log](https://github.com/DisplayLink/evdi/files/9900929/make.log)

**Comment by dimitarsh1** [comment]
```
$ git status
On branch devel
Your branch is up to date with 'origin/devel'.

nothing to commit, working tree clean
$ git pull
Already up to date.
```

I don't get the last comment ;)

**Comment by SimPilotAdamT** [comment]
@dimitarsh1 it might be a good idea to make another issue... Might be a bug in this PR that wasn't spotted. I'd ignore the last comment.

**Comment by Skesov** [comment]
When you push tag on these changes?
