### ISSUE TITLE
Module evdi not found in directory.

### ISSUE THREAD

**Issue by marc-cwm** [DisplayLink/evdi#492]
- Are you using the latest driver?     Yes.
- Are you using the latest EVDI version?     Yes.
- If you are using a DisplayLink device, have you checked 'troubleshooting' on DisplayLink's website?     Yes.
- Is this issue related to evdi/kernel?     Do not think so. 
- Linux distribution and its version: Arch Linux
- Linux kernel version: 6.10.10-zen1-1-zen
- Xorg version (if used): 1.21.1.13
- Desktop environment in use: KDE Plasma 6

I'm not sure if this is just a matter of it not being compatible, but after updating my system, the displaylink service no longer starts.  After digging through logs, we eventually get:
modprobe[105853]: modprobe: FATAL: Module evdi not found in directory /lib/modules/6.10.10-zen1-1-zen

This looks like it may have started after updating to 1.14.7.r3.g59a3a86-1, but I have not been able to get this working again using an older version.  This looks like it may be linked to #481 but it looks like that should have been fixed in the version I am currently on.

**Comment by SuperMeepBoy** [comment]
Can confirm. Happens to me too.

**Comment by tbalzer** [comment]
Same here.

```
==> dkms install --no-depmod evdi/1.14.7 -k 6.10.10-arch1-1
Error! Bad return status for module build on kernel: 6.10.10-arch1-1 (x86_64)
Consult /var/lib/dkms/evdi/1.14.7/build/make.log for more information.
```
The mentioned file contains a lot of errors like this, referring to a missing `tests/evdi_test.h` included from various files:
```
In file included from /var/lib/dkms/evdi/1.14.7/build/evdi_platform_dev.c:27:
/var/lib/dkms/evdi/1.14.7/build/evdi_drm_drv.h:41:10: fatal error: tests/evdi_test.h: No such file or directory
   41 | #include "tests/evdi_test.h"
      |          ^~~~~~~~~~~~~~~~~~~
```

**Comment by stonalampa** [comment]
Same thing happens to me :+1:

**Comment by tbalzer** [comment]
I've taken more of a look into the issue. Due to the added tests, the `PKGBUILD` of `evdi-git` in Arch needed some adjustments to make those files available.

However that only shifts the problem it seems. DKMS can then build the module, however it cannot be loaded:

`modprobe: ERROR: could not insert 'evdi': Unknown symbol in module, or unknown parameter (see dmesg)`

However `dmesg` is completely silent.

Same behavior if we build from source tarball in package `evdi` updated to `1.14.7`.

**Comment by JosemiGT** [comment]
Another one around here who has had the same problem in archlinux.

So far I have solved it by changing the `evdi-git` package in AUR to just `evdi` and with this version of the package it works.

The current `evdi` package in AUR that works is `1.14.6-0`

**Comment by stonalampa** [comment]
Also confirming that reverting to `1.14.6-0` fixes it. 
Installed `1.14.6`, removed `1.14.7` and rebooted.

**Comment by tbalzer** [comment]
The `1.14.6` `evdi` package works also for me after reboot, at least with 6.10 kernel.

I also first had issues when downgrading, but that might have been because I tried the `evdi-git` package with older revisions which led to issues for me.

For now I'm not updating to 6.11 then until `1.14.7` can be built.

**Comment by DocMAX** [comment]
What stupid things happen here?? DisplayLink breaks constantly!!

**Comment by arcenik** [comment]
This is a problem of aur package that did not included the **module/tests** directory. This is fixed in the last version.

See https://aur.archlinux.org/packages/evdi

```
--- PKGBUILD.orig       2024-10-10 10:59:10.000000000 -0700
+++ PKGBUILD    2024-10-10 11:00:18.019325725 -0700
@@ -29,4 +29,7 @@
   SRCDIR="$pkgdir/usr/src/$pkgname-$pkgver"    # This one is needed for dkms
   install -d "$SRCDIR"
   find module -maxdepth 1 -type f -exec install -m0644 '{}' "$SRCDIR" \;
+
+  install -d "$SRCDIR/tests"
+  find module/tests -maxdepth 1 -type f -exec install -m0644 '{}' "$SRCDIR/tests" \;
 }
```

**Comment by ADPenrose** [comment]
I have the last version of evdi (1.14.7-1) and out of the bloom I started getting this same error when initializing DisplayLink.
```
modprobe: FATAL: Module evdi not found in directory /lib/modules/6.12.1-arch1-1
```

**Comment by arcenik** [comment]
That is because it does not compile with linux-6.12 unless you do a small patch as explained in https://aur.archlinux.org/packages/evdi-git

Before you reboot to a new kernel, you can check that using **dkms status**. If you see **added** instead of **installed**, that means the module compilation failed and is not available.

**Comment by ADPenrose** [comment]
Before applying the patch, I managed to get evdi working just by using the evdi-git pacakge. The displaylink.service is initializing as expected, but my monitors are not being detected haha.

**Comment by browser-bug** [comment]
I keep getting this error thrown by modprobe whenever I upgrade linux headers. The `/lib/modules/` directory gets updated removing the old kernel module and replacing it with the newer. Everytime this happens the displaylink service fails because modprobe cannot found `evdi` anymore since it is still pointing to the old modules directory. Of course, doing a system reboot solves the issue.

Am I doing something wrong or is this expected?
