### ISSUE TITLE
Kernel module fails to build on mainline kernel 6.6-rc5

### ISSUE THREAD

**Issue by mrscottie** [DisplayLink/evdi#433]
* Are you using the latest driver? Yes (DisplayLink 5.8)
    
  * Are you using the latest EVDI version? 1.14.1
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? Yes
    
  * Is this issue related to evdi/kernel? Yes
    

  * Linux distribution and its version: Arch 
  * Linux kernel version: 6.6-rc5-mainline-1
  * Xorg version (if used): Wayland
  * Desktop environment in use: Plasma

The kernel module is failing to build on the latest mainline kernel (6.6-rc5). Below is the output from executing make:

make -C /lib/modules/6.6.0-rc5-1-mainline/build M=$PWD
make[1]: Entering directory '/usr/lib/modules/6.6.0-rc5-1-mainline/build'
  CC [M]  /usr/src/evdi/module/evdi_platform_drv.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_platform_dev.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_sysfs.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_modeset.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_connector.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_encoder.o
gcc: warning: include/drm: linker input file unused because linking not done
  CC [M]  /usr/src/evdi/module/evdi_drm_drv.o
/usr/src/evdi/module/evdi_drm_drv.c:127:31: error: ‘drm_gem_prime_fd_to_handle’ undeclared here (not in a function)
  127 |         .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/src/evdi/module/evdi_drm_drv.c:129:31: error: ‘drm_gem_prime_handle_to_fd’ undeclared here (not in a function)
  129 |         .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /usr/src/evdi/module/evdi_drm_drv.o] Error 1
make[2]: *** [/usr/lib/modules/6.6.0-rc5-1-mainline/build/Makefile:1913: /usr/src/evdi/module] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.0-rc5-1-mainline/build'
make: *** [Makefile:86: module] Error 2

The same output is produced if using dkms to build the module. I have uninstalled and reinstalled both the linux-mainline and linux-mainline-headers packages; however, the result is always the same.

This module was building and working fine on mainline kernel 6.3. After upgrading to mainline kernel 6.4 the module has failed to build.

I am currently using the kernel module for kernel 6.5.6 without issues.

**Comment by L422Y** [comment]
It also fails on 6.6-rc1

```bash
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C module
make[1]: Entering directory '/root/evdi/module'
make -C /lib/modules/6.6.0-rc1-edge-rockchip-rk3588/build M=$PWD
make[2]: Entering directory '/usr/src/linux-headers-6.6.0-rc1-edge-rockchip-rk3588'
  CC [M]  /root/evdi/module/evdi_platform_drv.o
  CC [M]  /root/evdi/module/evdi_platform_dev.o
  CC [M]  /root/evdi/module/evdi_sysfs.o
  CC [M]  /root/evdi/module/evdi_modeset.o
  CC [M]  /root/evdi/module/evdi_connector.o
  CC [M]  /root/evdi/module/evdi_encoder.o
  CC [M]  /root/evdi/module/evdi_drm_drv.o
/root/evdi/module/evdi_drm_drv.c:127:31: error: ‘drm_gem_prime_fd_to_handle’ undeclared here (not in a function)
  127 |         .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/root/evdi/module/evdi_drm_drv.c:129:31: error: ‘drm_gem_prime_handle_to_fd’ undeclared here (not in a function)
  129 |         .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[4]: *** [scripts/Makefile.build:243: /root/evdi/module/evdi_drm_drv.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.6.0-rc1-edge-rockchip-rk3588/Makefile:1913: /root/evdi/module] Error 2
make[2]: *** [Makefile:234: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.6.0-rc1-edge-rockchip-rk3588'
make[1]: *** [Makefile:86: module] Error 2
make[1]: Leaving directory '/root/evdi/module'
make: *** [Makefile:10: all] Error 2
```

**Comment by ziasquinn** [comment]
Can confirm:

```
make: *** [Makefile:10: all] Error 2
error: builder for '/nix/store/by4r6ygvs9r3mw9b9kc1nkl0i2x1jqrc-evdi-1.14.1.drv' failed with exit code 2
error: 1 dependencies of derivation '/nix/store/a1flmsznpk7mdl3hvjmihmnpf6xfzpim-displaylink-5.8.0-63.33.drv' failed to build
error: 1 dependencies of derivation '/nix/store/j03j48cbijs1vag278l159kjs5z9qxq4-kernel-modules.drv' failed to build
error (ignored): error: cannot unlink '/tmp/nix-build-nvidia-x11-545.23.06-6.6.0-xanmod1.drv-7/NVIDIA-Linux-x86_64-545.23.06/kernel': Directory not empty
error: 1 dependencies of derivation '/nix/store/f6x7z4agf7cj8ibdgq12myknjb5gj4x6-linux-6.6.0-xanmod1-modules.drv' failed to build
error: 1 dependencies of derivation '/nix/store/vf82qlsznacl3vjyaqci2aaw45nk2k7a-nixos-system-mother-23.11pre542330.0cbe9f69c234.drv' failed to build

```

**Comment by dominikzogg** [comment]
Kernel 6.6 was release and will arrive in Fedora in about 2 weeks and probably earlier in Arch. Any update on this?

**Comment by hafkensite** [comment]
Kernel 6.6 has indeed been released on arch, it fails to build the package on `6.6.1.arch1-1` with:
```
/var/lib/dkms/evdi/1.14.03/build/evdi_fb.c: In function ‘evdifb_create’:
/var/lib/dkms/evdi/1.14.03/build/evdi_fb.c:421:23: error: ‘FBINFO_DEFAULT’ undeclared (first use in this function)
  421 |         info->flags = FBINFO_DEFAULT;
      |                       ^~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.03/build/evdi_fb.c:421:23: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.03/build/evdi_fb.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/evdi/1.14.03/build/evdi_drm_drv.c:127:31: error: ‘drm_gem_prime_fd_to_handle’ undeclared here (not in a function)
  127 |         .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.03/build/evdi_drm_drv.c:129:31: error: ‘drm_gem_prime_handle_to_fd’ undeclared here (not in a function)
  129 |         .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.03/build/evdi_drm_drv.o] Error 1
make[2]: *** [/usr/lib/modules/6.6.1-arch1-1/build/Makefile:1913: /var/lib/dkms/evdi/1.14.03/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
```

**Comment by cedricroijakkers** [comment]
I'm just here waiting for the response from the DisplayLink maintainers saying that Arch/Nix/Fedora is not a supported distribution.

**Comment by dominikzogg** [comment]
@cedricroijakkers i do not believe that beeing passive agressive will convince the team to chamged the supported distribution(s). And within the last two years using it they were fast in adapt to new kernels long before they're used in Ubuntu, some versions never were.

**Comment by Kevinjil** [comment]
> No diea what I broke with this but my journal does not get flushed and all 3 screens are working fine again.
> 
> ```diff
> diff --git a/module/evdi_drm_drv.c b/module/evdi_drm_drv.c
> index 09a9da0..00b7402 100644
> --- a/module/evdi_drm_drv.c
> +++ b/module/evdi_drm_drv.c
> @@ -124,9 +124,7 @@ static struct drm_driver driver = {
>  
>         .fops = &evdi_driver_fops,
>  
> -       .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
>         .gem_prime_import = drm_gem_prime_import,
> -       .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
>  #if KERNEL_VERSION(5, 11, 0) <= LINUX_VERSION_CODE || defined(EL8)
>  #else
>         .preclose = evdi_driver_preclose,
> diff --git a/module/evdi_fb.c b/module/evdi_fb.c
> index 3789b33..4a4fb6a 100644
> --- a/module/evdi_fb.c
> +++ b/module/evdi_fb.c
> @@ -418,7 +418,6 @@ static int evdifb_create(struct drm_fb_helper *helper,
>         info->fix.smem_start = (unsigned long)efbdev->efb.obj->vmapping;
>  
>  #if KERNEL_VERSION(4, 20, 0) <= LINUX_VERSION_CODE || defined(EL8)
> -       info->flags = FBINFO_DEFAULT;
>  #else
>         info->flags = FBINFO_DEFAULT | FBINFO_CAN_FORCE_OUTPUT;
>  #endif
> ```
> 
> ```shell
>              .',;::::;,'.
>          .';:cccccccccccc:;,.
>       .;cccccccccccccccccccccc;.         crashdummy@crashphyrus 
>     .:cccccccccccccccccccccccccc:.       ---------------------- 
>   .;ccccccccccccc;.:dddl:.;ccccccc;.     OS: Fedora release 39 (Thirty Nine) x86_64 
>  .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Host: ROG Zephyrus G15 GA503RW_GA503RW 1.0 
> .:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Kernel: 6.6.1-0.rc1.350.vanilla.fc39.x86_64 
> ,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Uptime: 7 mins 
> :cccccccccccccc;MMM.;cccccccccccccccc:   Packages: 3580 (rpm), 68 (flatpak) 
> :ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   Shell: bash 5.2.15 
> cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   Resolution: 2560x1440 
> ccccc:XM0';cccc;MMM.;cccccccccccccccc'   DE: GNOME 45.1 
> ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    WM: Mutter 
> ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     WM Theme: Sweet-Dark 
> cccccc;dNMWXXXWM0::cccccccccccccc:,      Theme: Sweet-Dark-v40 [GTK2/3] 
> cccccccc;.:odl:.;cccccccccccccc:,.       Icons: candy-icons [GTK2/3] 
> :cccccccccccccccccccccccccccc:'.         Terminal: terminator 
> .:cccccccccccccccccccccc:;,..            CPU: AMD Ryzen 9 6900HS with Radeon Graphics (16) @ 4.925GHz 
>   '::cccccccccccccc::;,.                 GPU: NVIDIA Geforce RTX 3070 Ti Laptop GPU 
>                                          GPU: AMD ATI Radeon 680M 
>                                          Memory: 5270MiB / 31323MiB 
> ```

Tried applying this patch. The module builds with the patch, but no displays are detected.

**Comment by DocMAX** [comment]
Same here. No display. Going back to 6.59 works.

**Comment by cedricroijakkers** [comment]
This PR https://github.com/DisplayLink/evdi/pull/436 has fixed the issue for me. It's now working on Arch Linux using DisplayLink 5.8, the `devel` branch of this repo, and kernel 6.6.1.

**Comment by DocMAX** [comment]
ok, now maintainers please merge. thanks.

**Comment by Kevinjil** [comment]
> [snip]
> Sorry I'm late to respond.
The metnioned PR is basically exactly the same implementation.
It just added some compiler flags to allow backwards compatibility.
>
> I tested it on about 20 devices running either EOS, Fedora or Ubuntu.
I had some issues with upgrading from 1.12.0 in the past maybe that one happened here again.
>
> You can try applying the patch of the PR as well.
If you're on Fedora 37/38/39 I can provide you a rpm package if you want to

At this point I'm kind of puzzled what DocMAX and I did wrong yesterday. The latest `devel` branch does also build but actually functions correctly.

**Comment by cedricroijakkers** [comment]
@Kevinjil I did have some funkyness too, a restart of the displaylink service or a reboot did the trick however.

**Comment by displaylink-emajewsk** [comment]
Once loaded, `evdi` will stay in the kernel until a reboot. Just a hunch, but if you've had an earlier version of `evdi` loaded, the displaylink driver will detect the discrepancy and refuse serving the displays.

**Comment by DocMAX** [comment]
i deleted the dkms evdi folder and recompiled the module with no errors. but doesn't work with 6.6. worked on 6.5 though.

**Comment by DocMAX** [comment]
hmm, no, that wasn't the solution. no idea why the displays are detected randomly

**Comment by bf** [comment]
I also get the following error on `6.6.1-arch1-1` when doing `dkms install --no-depmod evdi/1.14.1 -k 6.6.1-arch1-1 --verbose`. Did anybody resolve this issue?

```
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.1/build/evdi_fb.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.c:127:31: error: ‘drm_gem_prime_fd_to_handle’ undeclared here (not in a function)
  127 |         .prime_fd_to_handle = drm_gem_prime_fd_to_handle,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.c:129:31: error: ‘drm_gem_prime_handle_to_fd’ undeclared here (not in a function)
  129 |         .prime_handle_to_fd = drm_gem_prime_handle_to_fd,
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/evdi/1.14.1/build/evdi_drm_drv.o] Error 1
make[2]: *** [/usr/lib/modules/6.6.1-arch1-1/build/Makefile:1913: /var/lib/dkms/evdi/1.14.1/build] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.1-arch1-1/build'
make: *** [Makefile:38: all] Error 2
```

dkms error:

```Sign command: /usr/lib/modules/6.6.1-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
make clean KERNELRELEASE=6.6.1-arch1-1 DKMS_BUILD=1
/lib/modules/6.6.1-arch1-1/build
make KBUILD_VERBOSE=1 M=/var/lib/dkms/evdi/1.14.1/build SUBDIRS=/var/lib/dkms/evdi/1.14.1/build SRCROOT=/var/lib/dkms/evdi/1.14.1/build -C /lib/modules/6.6.1-arch1-1/build clean
make[1]: Entering directory '/usr/lib/modules/6.6.1-arch1-1/build'
make --no-print-directory -C /usr/lib/modules/6.6.1-arch1-1/build \
-f /usr/lib/modules/6.6.1-arch1-1/build/Makefile clean
make -f ./scripts/Makefile.clean obj=/var/lib/dkms/evdi/1.14.1/build
# cmd_rmfiles clean
  rm -rf /var/lib/dkms/evdi/1.14.1/build/Module.symvers /var/lib/dkms/evdi/1.14.1/build/modules.nsdeps /var/lib/dkms/evdi/1.14.1/build/compile_commands.json /var/lib/dkms/evdi/1.14.1/build/.thinlto-cache
make[1]: Leaving directory '/usr/lib/modules/6.6.1-arch1-1/build'

{ make -j8 KERNELRELEASE=6.6.1-arch1-1 all INCLUDEDIR=/lib/modules/6.6.1-arch1-1/build/include KVERSION=6.6.1-arch1-1 DKMS_BUILD=1; } >> /var/lib/dkms/evdi/1.14.1/build/make.log 2>&1
(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.6.1-arch1-1 (x86_64)
Consult /var/lib/dkms/evdi/1.14.1/build/make.log for more information.
```

**Comment by Typografikon** [comment]
Any update to this issue?

**Comment by mrscottie** [comment]
The module builds for me and loads on kernel 6.6-rc5 and now 6.7-rc3.

**Comment by cedricroijakkers** [comment]
@mrscottie or one of the maintainers @displaylink-emajewsk @displaylink-dkurek @displaylink-mlukaszek: This issue can be closed, it has been resolved. Building from the git repo works now, possibly you need to create a new release to finalise it.

**Comment by nathan-weinberg** [comment]
> > [dmenezes@alienware-f15 ~]$ neofetch .',;::::;,'. dmenezes@alienware-f15 .';:cccccccccccc:;,. ---------------------- .;cccccccccccccccccccccc;. OS: Fedora Linux 39 (Workstation Edition) x86_64 .:cccccccccccccccccccccccccc:. Host: Alienware m15 R6 .;ccccccccccccc;.:dddl:.;ccccccc;. Kernel: 6.6.2-201.fc39.x86_64 .:ccccccccccccc;OWMKOOXMWd;ccccccc:. Uptime: 33 mins .:ccccccccccccc;KMMc;cc;xMMc:ccccccc:. Packages: 2994 (rpm), 90 (flatpak) ,cccccccccccccc;MMM.;cc;;WW::cccccccc, Shell: bash 5.2.21 :cccccccccccccc;MMM.;cccccccccccccccc: Resolution: 1920x1080, 1920x1080, 1920x1080, 1080x1920 :ccccccc;oxOOOo;MMM0OOk.;cccccccccccc: DE: GNOME 45.1 cccccc:0MMKxdd:;MMMkddc.;cccccccccccc; WM: Mutter ccccc:XM0';cccc;MMM.;cccccccccccccccc' WM Theme: Adwaita ccccc;MMo;ccccc;MMW.;ccccccccccccccc; Theme: Adwaita-dark [GTK2/3] ccccc;0MNc.ccc.xMMd:ccccccccccccccc; Icons: Adwaita [GTK2/3] cccccc;dNMWXXXWM0::cccccccccccccc:, Terminal: gnome-terminal cccccccc;.:odl:.;cccccccccccccc:,. CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz :cccccccccccccccccccccccccccc:'. GPU: Intel TigerLake-H GT1 [UHD Graphics] .:cccccccccccccccccccccc:;,.. GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q '::cccccccccccccc::;,. Memory: 7180MiB / 64031MiB
> > [dmenezes@alienware-f15 ~]$ [dmenezes@alienware-f15 ~]$ sudo fpaste /var/lib/dkms/evdi/1.14.1/build/make.log Uploading (41.1KiB)... https://paste.centos.org/view/6ad05920
> 
> Looks like you dont use the applied patch. Can you try one of mine ? https://github.com/SimonSchwendele/displaylink-rpm/releases/tag/v1.14.1-3

Just wanted to chime in - I'm on Fedora 38 with kernel `6.6.2-101.fc38.x86_64` - the [current released version upstream](https://github.com/displaylink-rpm/displaylink-rpm/releases/tag/v5.8.0) for the displaylink-rpm stopped working for me but this RPM from the fork fixed the issue

**Comment by cristobal87** [comment]
Hi @Crashdummyy,
I am on fedora 39 (Linux 6.6.2-201.fc39.x86_64) and having the same issue as everybody here, and when I tried running your patched rpm, it displayed an error saying it was conflicting with the previous packages. I understand I need to remove the previous packages, but I am not exactly versed in how I can achieve that... any chance you could help me out and tell me how I can remove/clean the previous installation so I can install your version?

Thank you very much!

**Comment by vladgitdev** [comment]
> > [dmenezes@alienware-f15 ~]$ neofetch .',;::::;,'. dmenezes@alienware-f15 .';:cccccccccccc:;,. ---------------------- .;cccccccccccccccccccccc;. OS: Fedora Linux 39 (Workstation Edition) x86_64 .:cccccccccccccccccccccccccc:. Host: Alienware m15 R6 .;ccccccccccccc;.:dddl:.;ccccccc;. Kernel: 6.6.2-201.fc39.x86_64 .:ccccccccccccc;OWMKOOXMWd;ccccccc:. Uptime: 33 mins .:ccccccccccccc;KMMc;cc;xMMc:ccccccc:. Packages: 2994 (rpm), 90 (flatpak) ,cccccccccccccc;MMM.;cc;;WW::cccccccc, Shell: bash 5.2.21 :cccccccccccccc;MMM.;cccccccccccccccc: Resolution: 1920x1080, 1920x1080, 1920x1080, 1080x1920 :ccccccc;oxOOOo;MMM0OOk.;cccccccccccc: DE: GNOME 45.1 cccccc:0MMKxdd:;MMMkddc.;cccccccccccc; WM: Mutter ccccc:XM0';cccc;MMM.;cccccccccccccccc' WM Theme: Adwaita ccccc;MMo;ccccc;MMW.;ccccccccccccccc; Theme: Adwaita-dark [GTK2/3] ccccc;0MNc.ccc.xMMd:ccccccccccccccc; Icons: Adwaita [GTK2/3] cccccc;dNMWXXXWM0::cccccccccccccc:, Terminal: gnome-terminal cccccccc;.:odl:.;cccccccccccccc:,. CPU: 11th Gen Intel i7-11800H (16) @ 4.600GHz :cccccccccccccccccccccccccccc:'. GPU: Intel TigerLake-H GT1 [UHD Graphics] .:cccccccccccccccccccccc:;,.. GPU: NVIDIA GeForce RTX 3070 Mobile / Max-Q '::cccccccccccccc::;,. Memory: 7180MiB / 64031MiB
> > [dmenezes@alienware-f15 ~]$ [dmenezes@alienware-f15 ~]$ sudo fpaste /var/lib/dkms/evdi/1.14.1/build/make.log Uploading (41.1KiB)... https://paste.centos.org/view/6ad05920
> 
> Looks like you dont use the applied patch. Can you try one of mine ? https://github.com/SimonSchwendele/displaylink-rpm/releases/tag/v1.14.1-3

Finally I got it back on Fedora 39! Thank you @Crashdummyy.

A step-by-step list of what I did, in case it is useful for somebody:

```
sudo dnf install fedora-packager rpmdevtools
sudo dnf install libdrm-devel glibc-devel.i686

git clone https://github.com/SimonSchwendele/displaylink-rpm

cd displaylink-rpm

make

sudo dnf autoremove displaylink
sudo dkms remove evdi/<version> -a
sudo rm -rf /var/lib/dkms/evdi

sudo dnf install x86_64/displaylink-1.14.1-*.rpm
```

After the last command my external displays immediately came back to life.

**Comment by mrscottie** [comment]
Closing since this has been fixed.

**Comment by proffalken** [comment]
I'd argue that this is only "fixed" once a release has been cut?

I've just come back to using DisplayLink on a pop!_OS (Ubuntu variant) laptop running the ominously versioned `6.6.6-76060606-generic` and the current apt packages do not contain the above fix.

I can build from source for now, but that still strikes me as half a solution rather than "just upgrade via the usual channels and everything will be working again"?

**Comment by humanplayer2** [comment]
> I'd argue that this is only "fixed" once a release has been cut?
> 
> I've just come back to using DisplayLink on a pop!_OS (Ubuntu variant) laptop running the ominously versioned `6.6.6-76060606-generic` and the current apt packages do not contain the above fix.
> 
> I can build from source for now, but that still strikes me as half a solution rather than "just upgrade via the usual channels and everything will be working again"?

I, too, am on Pop with same kernel. Can you tell me what you did to build and install from source?

**Comment by clagiordano** [comment]
> * Clone the evdi repo to someplace
> * Copy everything in the `module` directory to `/usr/src/evdi-1.14.1`

This worked for me on Debian Sid with kernel 6.6.13

Thanks!

**Comment by pevogam** [comment]
> https://github.com/SimonSchwendele/displaylink-rpm

And better yet, Simon's page also has artifact RPM-s that are automatically posted in releases:
https://github.com/displaylink-rpm/displaylink-rpm/releases

**Comment by pevogam** [comment]
> > > https://github.com/SimonSchwendele/displaylink-rpm
> > 
> > 
> > And better yet, Simon's page also has artifact RPM-s that are automatically posted in releases: https://github.com/displaylink-rpm/displaylink-rpm/releases
> 
> The above one is a fork. The main reason for this fork is that it automatically pushes them into my copr. https://copr.fedorainfracloud.org/coprs/crashdummy/Displaylink/

I see, even better then!

**Comment by cristobal87** [comment]
> > > > > https://github.com/SimonSchwendele/displaylink-rpm
> > > > 
> > > > 
> > > > And better yet, Simon's page also has artifact RPM-s that are automatically posted in releases: https://github.com/displaylink-rpm/displaylink-rpm/releases
> > > 
> > > 
> > > The above one is a fork. The main reason for this fork is that it automatically pushes them into my copr. https://copr.fedorainfracloud.org/coprs/crashdummy/Displaylink/
> > 
> > 
> > hey @Crashdummyy, first things first, thank you very much for sharing this, I have been using your fork for a while now and it has worked like magic.
> > However, I just got a new computer and it has secure boot enabled. I followed the procedure described in your copr, and my problem is the final step... this is the first time I actually use secure boot so after registering the MOK, I dont know how to sign the module. Any chance you could teach me that? Cheers!
> 
> I dont use secureboot at all so its been ages since I last signed a module. Imho its snakeoil and a pain the ass as you need to sign all modules after every kernel update.
> 
> Well nevermind the instructions should create and import the cert.
> 
> You should now be able to sign your module.
> 
> ```shell
> $ sudo unxz $(modinfo -n evdi)
> 
> $ sudo /usr/src/kernels/$(uname -r)/scripts/sign-file sha256 ./MOK.priv  ./MOK.der /lib/modules/$(uname -r)/extra/evdi.ko
> 
> $ sudo xz -f /lib/modules/$(uname -r)/extra/evdi.ko
> ```
> 
> Your evdi.ko.xz should then be signed in case no error occurred

thank you so much! I didnt realized that these steps were right in front of me in the instructions, or I just didn't realized that was the procedure for signing. It worked like a charm.

Well, I kind of convinced the IT guys at work to let me continue using fedora instead of windows so they installed it with secure boot... I might end up negotiating a bit further. 

Anyways, thank you very much, you are a legend.
