### PR TITLE
Fix tests and build for kernels >= 4.15.0

### LINKED ISSUE #117: Linux 4.15 already ships the drm_file*
...which means I'll have to apply this patch to make the bulid work. Please do some research on version numbers before adding these preprocessor checks.

```
diff --git a/module/evdi_connector.c b/module/evdi_connector.c
index 811b85a..69a98b9 100644
--- a/module/evdi_connector.c
+++ b/module/evdi_connector.c
@@ -85,7 +85,7 @@ static struct drm_encoder *evdi_best_single_encoder(struct drm_connector
        int enc_id = connector->encoder_ids[0];

        return drm_encoder_find(connector->dev,
-#if KERNEL_VERSION(4, 16, 0) <= LINUX_VERSION_CODE
+#if KERNEL_VERSION(4, 15, 0) <= LINUX_VERSION_CODE
                                 NULL,
 #endif
                                 enc_id);
```

### PR DESCRIPTION
**Pull request by jtdoepke**
This is basically a duplicate of #118, but with @xblitz's comment applied. Fixes #117. Also gets Travis-CI tests passing.

I'm a little uncertain about my test fixes; this is the first time I've worked with anything Linux kernel-related.

### CODE REVIEW

File: module/evdi_debug.h [hunk 1]
```diff
@@ -19,9 +19,13 @@
 
 extern unsigned int evdi_loglevel;
 
+// This definition is to get checkpatch.pl to stop complaining.
+// TODO: Refactor all this to use pr_<level> and dev_dbg and stuff.
```
Comment (jtdoepke) [inline module/evdi_debug.h]: I could be wildly off base with this TODO?

**Comment by rgarcia89** [comment]
Worked for me. Thanks a lot

**Comment by enricoT** [comment]
I compiled but i get an error on linux-ck-ivy kernel

DKMS: install completed.
:: Running post-transaction hooks...
(1/2) Install DKMS modules
==> dkms install evdi/1.5.0.r11.ga73092d -k 4.15.7-1-ARCH
Error! Bad return status for module build on kernel: 4.15.7-1-ARCH (x86_64)
Consult /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/make.log for more information.
==> dkms install evdi/1.5.0.r11.ga73092d -k 4.14.23-1-lts
==> dkms install evdi/1.5.0.r11.ga73092d -k 4.15.7-1-ck-ivybridge
Error! Bad return status for module build on kernel: 4.15.7-1-ck-ivybridge (x86_64)
Consult /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/make.log for more information.
(2/2) Arming ConditionNeedsUpdate...

**Comment by jtdoepke** [comment]
I suspect your error is unrelated to this PR, but what's in the `/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/make.log` log it speaks of?

**Comment by enricoT** [comment]
[code]
/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c: In function ‘evdi_best_single_encoder’:
/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c:91:6: warning: passing argument 2 of ‘drm_encoder_find’ makes pointer from integer without a cast [-Wint-conversion]
      enc_id);
      ^~~~~~
In file included from ./include/drm/drm_modeset_helper_vtables.h:33:0,
                 from ./include/drm/drm_crtc_helper.h:43,
                 from /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c:16:
./include/drm/drm_encoder.h:217:35: note: expected ‘struct drm_file *’ but argument is of type ‘int’
 static inline struct drm_encoder *drm_encoder_find(struct drm_device *dev,
                                   ^~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c:87:9: error: too few arguments to function ‘drm_encoder_find’
  return drm_encoder_find(connector->dev,
         ^~~~~~~~~~~~~~~~
In file included from ./include/drm/drm_modeset_helper_vtables.h:33:0,
                 from ./include/drm/drm_crtc_helper.h:43,
                 from /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c:16:
./include/drm/drm_encoder.h:217:35: note: declared here
 static inline struct drm_encoder *drm_encoder_find(struct drm_device *dev,
                                   ^~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c:92:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make[2]: *** [scripts/Makefile.build:316: /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.o] Error 1
make[2]: *** Waiting for unfinished jobs....
  if [ "-pg" = "-pg" ]; then if [ /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_modeset.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_modeset.o"; fi; fi;
   ./tools/objtool/objtool orc generate --no-fp  "/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/.tmp_evdi_drv.o";
   ./tools/objtool/objtool orc generate --no-fp  "/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/.tmp_evdi_encoder.o";
  if [ "-pg" = "-pg" ]; then if [ /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_drv.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_drv.o"; fi; fi;
  if [ "-pg" = "-pg" ]; then if [ /var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_encoder.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_encoder.o"; fi; fi;
make[1]: *** [Makefile:1515: _module_/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.15.7-1-ck-ivybridge/build'
make: *** [Makefile:22: all] Error 2
[/code]
Sorry if this is not what you need, is the end of log

**Comment by jtdoepke** [comment]
Ok, that does sound related. Can you look at `/var/lib/dkms/evdi/1.5.0.r11.ga73092d/build/evdi_connector.c` and make sure there's a function `evdi_best_single_encoder` that looks like this:

```c
static struct drm_encoder *evdi_best_single_encoder(struct drm_connector
                                                    *connector)
{
        int enc_id = connector->encoder_ids[0];

        return drm_encoder_find(connector->dev,
#if KERNEL_VERSION(4, 15, 0) <= LINUX_VERSION_CODE
                                 NULL,
#endif
                                 enc_id);
}
```

**Comment by mateusduboli** [comment]
+1

**Comment by laurenblackfox** [comment]
Any idea when this will enter a release? It's been sat here for ages ... I'd really like to update my kernel without my displays breaking :/

**Comment by jtdoepke** [comment]
This seems to have been [fixed in v1.5.0.2](https://github.com/DisplayLink/evdi/blame/v1.5.0.2/module/evdi_connector.c#L88)... somehow. My commit that actually makes the fix seems to be gone, so I'm guessing history editing is involved.
