### ISSUE TITLE
evdi breaks with Kernel v5.14.0-687.12.1.el9_8.x86_64

### ISSUE THREAD

**Issue by WallaceDog** [DisplayLink/evdi#573]
$ make
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C module 
make[1]: Entering directory '/home/wallace/evdi-main/module'
make -C /lib/modules/5.14.0-687.12.1.el9_8.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/5.14.0-687.12.1.el9_8.x86_64'
  CC [M]  /home/wallace/evdi-main/module/evdi_modeset.o
/home/wallace/evdi-main/module/evdi_modeset.c:501:22: error: initialization of ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_format_info *, const struct drm_mode_fb_cmd2 *)’ from incompatible pointer type ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_mode_fb_cmd2 *)’ [-Werror=incompatible-pointer-types]
  501 |         .fb_create = evdi_fb_user_fb_create,
      |                      ^~~~~~~~~~~~~~~~~~~~~~
/home/wallace/evdi-main/module/evdi_modeset.c:501:22: note: (near initialization for ‘evdi_mode_funcs.fb_create’)
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:250: /home/wallace/evdi-main/module/evdi_modeset.o] Error 1
make[2]: *** [Makefile:1968: /home/wallace/evdi-main/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-687.12.1.el9_8.x86_64'
make[1]: *** [Makefile:87: module] Error 2
make[1]: Leaving directory '/home/wallace/evdi-main/module'
make: *** [Makefile:13: module] Error 2

Downloaded evdi-main from GitHub 2026-06-05 
My system is Rocky  Linux  release 9.8 (Blue Onyx) with Kernel 5.14.0-687.12.1.el9_8.x86_64

**Comment by WallaceDog** [comment]
Just tried with 'richgieg' fix "Fix module build on EL 9.8 and 10.2#570", but get a different error.

$ make
CFLAGS="-isystem./include -isystem./include/uapi -Werror -Wextra -Wall -Wno-error=missing-field-initializers -Werror=sign-compare -Wmissing-prototypes -Wstrict-prototypes -Werror=discarded-qualifiers " make -C module 
make[1]: Entering directory '/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module'
make -C /lib/modules/5.14.0-687.12.1.el9_8.x86_64/build M=$PWD
make[2]: Entering directory '/usr/src/kernels/5.14.0-687.12.1.el9_8.x86_64'
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_platform_drv.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_platform_dev.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_sysfs.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_modeset.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_connector.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_encoder.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_drm_drv.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_fb.o
  CC [M]  /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.o
/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.c: In function ‘evdi_gem_mmap’:
/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.c:473:38: error: unused parameter ‘dev’ [-Werror=unused-parameter]
  473 |                   struct drm_device *dev, uint32_t handle, uint64_t *offset)
      |                   ~~~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
make[3]: *** [scripts/Makefile.build:250: /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.o] Error 1
make[2]: *** [Makefile:1968: /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module] Error 2
make[2]: Leaving directory '/usr/src/kernels/5.14.0-687.12.1.el9_8.x86_64'
make[1]: *** [Makefile:87: module] Error 2
make[1]: Leaving directory '/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module'
make: *** [Makefile:13: module] Error 2

**Comment by richgieg** [comment]
Seems that when running make from the root directory the build is more strict than when running make from within the module directory. As a workaround / test, can you try changing into the module directory first and then run make? I think it should succeed then.

**Comment by richgieg** [comment]
I submitted a fix in PR #574 to fix this issue:

```
CC [M] /home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.o
/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.c: In function ‘evdi_gem_mmap’:
/home/wallace/evdi-fix-el-build-for-9-8-and-10-2/module/evdi_gem.c:473:38: error: unused parameter ‘dev’ [-Werror=unused-parameter]
473 | struct drm_device *dev, uint32_t handle, uint64_t *offset)
| ~~~~~~~~~~~~~~~~~~~^~~
cc1: all warnings being treated as errors
```

**Comment by WallaceDog** [comment]
Thanks Richard. Using your #570 and running make in the module directory has resolved this for me.

**Comment by dbray925** [comment]
Seem to be having the same (or similar?) issue with the exact kernel you have above on a clean Rocky Linux 9 install. When I get to this part:

`sudo dkms autoinstall`

I'm getting:
```
Sign command: /lib/modules/5.14.0-687.12.1.el9_8.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Autoinstall of module evdi/1.14.16 for kernel 5.14.0-687.12.1.el9_8.x86_64 (x86_64)
Building module(s)...(bad exit status: 2)
Failed command:
make -j8 KERNELRELEASE=5.14.0-687.12.1.el9_8.x86_64 all INCLUDEDIR=/lib/modules/5.14.0-687.12.1.el9_8.x86_64/build/include KVERSION=5.14.0-687.12.1.el9_8.x86_64 DKMS_BUILD=1

Error! Bad return status for module build on kernel: 5.14.0-687.12.1.el9_8.x86_64 (x86_64)
Consult /var/lib/dkms/evdi/1.14.16/build/make.log for more information.

Autoinstall on 5.14.0-687.12.1.el9_8.x86_64 failed for module(s) evdi(10).

Error! One or more modules failed to install during autoinstall.
```

Reason found in /var/lib/dkms/evdi/1.14.16/build/make.log:
```
/var/lib/dkms/evdi/1.14.16/build/evdi_fb.c: In function ‘evdi_framebuffer_init’:
/var/lib/dkms/evdi/1.14.16/build/evdi_fb.c:222:40: error: passing argument 3 of ‘drm_helper_mode_fill_fb_struct’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  222 |                                        mode_cmd);
      |                                        ^~~~~~~~
      |                                        |
      |                                        const struct drm_mode_fb_cmd2 *
In file included from ./include/drm/drm_atomic_helper.h:33,
                 from ./include/drm/drm_damage_helper.h:35,
                 from /var/lib/dkms/evdi/1.14.16/build/evdi_fb.c:27:
./include/drm/drm_modeset_helper.h:37:67: note: expected ‘const struct drm_format_info *’ but argument is of type ‘const struct drm_mode_fb_cmd2 *’
   37 |                                     const struct drm_format_info *info,
      |                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/var/lib/dkms/evdi/1.14.16/build/evdi_fb.c:218:9: error: too few arguments to function ‘drm_helper_mode_fill_fb_struct’
  218 |         drm_helper_mode_fill_fb_struct(dev, &efb->base,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/drm/drm_atomic_helper.h:33,
                 from ./include/drm/drm_damage_helper.h:35,
                 from /var/lib/dkms/evdi/1.14.16/build/evdi_fb.c:27:
./include/drm/drm_modeset_helper.h:35:6: note: declared here
   35 | void drm_helper_mode_fill_fb_struct(struct drm_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.16/build/evdi_modeset.c:501:22: error: initialization of ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_format_info *, const struct drm_mode_fb_cmd2 *)’ from incompatible pointer type ‘struct drm_framebuffer * (*)(struct drm_device *, struct drm_file *, const struct drm_mode_fb_cmd2 *)’ [-Werror=incompatible-pointer-types]
  501 |         .fb_create = evdi_fb_user_fb_create,
      |                      ^~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/evdi/1.14.16/build/evdi_modeset.c:501:22: note: (near initialization for ‘evdi_mode_funcs.fb_create’)
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/evdi/1.14.16/build/evdi_fb.o] Error 1
```

Is there an extra step I need to perform to get the rocky-9-displaylink-1.14.16-1.github_evdi.x86_64.rpm installed? The exact steps I'm following are:
```
wget https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v6.2.0-1/rocky-9-displaylink-1.14.16-1.github_evdi.x86_64.rpm
sudo dnf -y install ./rocky-9-displaylink-1.14.16-1.github_evdi.x86_64.rpm
sudo dkms autoinstall
```

**Comment by richgieg** [comment]
Hi @dbray925, until the fix is merged (#570 or #572), this workaround should get the module build working:

```
sudo sed -i 's/CENTOS9/EL9/g' /usr/src/evdi-1.14.16/*.{c,h}
```

Then, run `sudo dkms autoinstall` again.

**Comment by dbray925** [comment]
Worked perfectly, thank you so much.

**Comment by synaptics-lspintzyk** [comment]
Fixed in 1.15.0. closing. 
If it is still there we can reopen.
