### ISSUE TITLE
Compile issue on Fedora 26 with 4.12 kernel

### ISSUE THREAD

**Issue by devoptimist** [DisplayLink/evdi#96]
DisplayLink was working fine on my Fedora 26 system on the 4.11.11 kernel, This morning I updated to 4.12.5 however DisplayLink now wont start.
I remove previous install and tried a recompile and received the following errors:
```
/var/lib/dkms/evdi/1.4.1/build/evdi_modeset.c:294:15: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]               
  .page_flip = evdi_crtc_page_flip,                                                                                                                           
               ^~~~~~~~~~~~~~~~~~~                                                                                                                            
/var/lib/dkms/evdi/1.4.1/build/evdi_modeset.c:294:15: note: (near initialization for ‘evdi_crtc_funcs.page_flip’)                                             
/var/lib/dkms/evdi/1.4.1/build/evdi_drv.c: In function ‘evdi_platform_probe’:                                                                                 
/var/lib/dkms/evdi/1.4.1/build/evdi_drv.c:120:9: error: implicit declaration of function ‘drm_platform_init’; did you mean ‘early_platform_init’? [-Werror=implicit-function-declaration]                                                                                                                                    
  return drm_platform_init(&driver, pdev);                                                                                                                    
         ^~~~~~~~~~~~~~~~~                  
```
I guess there was a breaking change in this kernel, let me know if you need any more info

**Comment by devoptimist** [comment]
Looks like there may be a fix fir this in the development branch:
https://github.com/DisplayLink/evdi/commit/6c689d69457820512f25204d83f0880824a932f3

**Comment by chlongv** [comment]
I can confirm that the above patch fixes the build of the driver for fedora 26 with latest 4.12 kernel and the module is loaded successfully.

However, displaylink currently does not work with fedora 26. Starting with the previous 4.11 kernel produces similar errors. I guess some other package updates have broken the current displaylink .rpm for fedora 26.

**Comment by devoptimist** [comment]
@chlongv thanks for confirming, just in case you are interested displaylink works for me on Fedora 26 kernel 4.11, however I am not using wayland.
some system info:
```
[~]$ uname -r                                                                                                                                
4.11.11-300.fc26.x86_64                                                                                                                                       
[~]$ echo $XDG_SESSION_TYPE                                                                                                                  
x11                                                                                                                                                           
[~]$ rpm -qa | grep displaylink                                                                                                              
displaylink-1.4.1-4.x86_64                                                                                                                                    
[~]$ systemctl status displaylink.service                                                                                                    
● displaylink.service - DisplayLink Manager Service                                                                                                           
   Loaded: loaded (/usr/lib/systemd/system/displaylink.service; static; vendor preset: disabled)
   Active: active (running) since Wed 2017-08-16 08:09:50 BST; 1h 36min ago
  Process: 1454 ExecStartPre=/sbin/modprobe evdi (code=exited, status=0/SUCCESS)
 Main PID: 1460 (DisplayLinkMana)
    Tasks: 26 (limit: 4915)
   CGroup: /system.slice/displaylink.service
           └─1460 /usr/libexec/displaylink/DisplayLinkManager

Aug 16 08:09:50 localhost.localdomain systemd[1]: Starting DisplayLink Manager Service...
Aug 16 08:09:50 localhost.localdomain systemd[1]: Started DisplayLink Manager Service.
```

**Comment by chlongv** [comment]
@devoptimist Thanks for your reply, it helped a lot. I had forgotten to manually enable/start the displaylink service. I can now confirm that with the above patch for the kernel module (and the service enabled), displaylink works (with X11 and not wayland of course) with F26.

**Comment by devoptimist** [comment]
works for me on 4.12.5 as well, thanks for this

**Comment by hjaltioj** [comment]
@devoptimist do you know how to get it to work on openSUSE Tumbleweed 42.3?
