### ISSUE TITLE
Fail to compile evdi on Fedora 35 with kernel 5.16.20 

### ISSUE THREAD

**Issue by agun76** [DisplayLink/evdi#348]
* Are you using the latest driver? yes, 1.9.1.3 (https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.4.1-1/fedora-35-displaylink-1.9.1-3.x86_64.rpm)
     
  * Are you using the latest EVDI version? yes, 1.9.1
    
  * If you are using a DisplayLink device, have you checked 'troubleshooting'
    on DisplayLink's website? 
    
  * Is this issue related to evdi/kernel? I think so.
    

  * Linux distribution and its version : Fedora 35 
  * Linux kernel version : 5.16.20
  * Xorg version (if used) : plasma KDE X11
  * Desktop environment in use : plasma KDE X11

Are you using the latest driver? yes, 1.9.1.3 (https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.4.1-1/fedora-35-displaylink-1.9.1-3.x86_64.rpm)
Linux distribution and its version : Fedora 35 
Linux kernel version : 5.16.20
Xorg version (if used) : plasma KDE X11
Desktop environment in use : plasma KDE X11.

display link does not work after upgrading the kernel (from 5.15.18 to 5.16.20). try to reinstall with the latest rpm of Display service (ttps://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.4.1-1/fedora-35-displaylink-1.9.1-3.x86_64.rpm), but it fail during compiling the evdi module. Initially because of irq-things, and try to resolve with (https://github.com/DisplayLink/evdi/commit/288f4b62b5ee2ed9b4430c32a875da85d03c1a24#) . but now the error is different. See make.log below:

"/var/lib/dkms/evdi/1.9.1/build/evdi_ioc32.c: In function ‘compat_evdi_connect’:
/var/lib/dkms/evdi/1.9.1/build/evdi_ioc32.c:64:19: error: implicit declaration of function ‘compat_alloc_user_space’"

detail as attached 
[make.log](https://github.com/DisplayLink/evdi/files/8040227/make.log)

any help/idea would be appreciated

**Comment by displaylink-emajewsk** [comment]
displaylink-rpm is a third party package, and seems to be outdated. the newest evdi is 1.10.0 and it supports linux kernels up to version 5.16 (haven't checked 5.17 yet)

**Comment by elguero** [comment]
Hey Emilia,

When will 5.5 (which has evdi 1.10 support) be taken out of beta? That is the hold up. In that repo.

Also, there were some fixes around working on EL8 kernels merged that are not in the current 1.10.0 release. When can we expect an updated version?

Thanks

**Comment by displaylink-emajewsk** [comment]
@elguero I don't think I can disclose any specific date, I'm afraid, sorry. The plan was to have it released by now, but a delay couldn't be helped.

**Comment by displaylink-emajewsk** [comment]
@elguero Hi, the release is up on the website. I'll close this issue now.

**Comment by elguero** [comment]
@agun76 The changes for v5.5 were committed yesterday. A release will be out soon.

Thanks @displaylink-emajewsk !

**Comment by agun76** [comment]
It works !!
Many thanks all ..
@displaylink-emajewsk. I'm sorry I didn't realize  that I download the old one. 

again many thanks !!

**Comment by xtermi2** [comment]
> displaylink-rpm is a third party package, and seems to be outdated. the newest evdi is 1.10.0 and it supports linux kernels up to version 5.16 (haven't checked 5.17 yet)

Kernel `5.17` is working fine with evdi `1.10.1` on my ubuntu 21.10 :+1:

**Comment by displaylink-emajewsk** [comment]
> Kernel `5.17` is working fine with evdi `1.10.1` on my ubuntu 21.10 👍

Thanks for the info. 😇 We're already working on ubuntu 22.04
